#!/bin/bash -l
# declare a name for this job
#PBS -N rl_pulse_PPO

# request the queue (enter the possible names, if omitted, default is the default)
# this job is going to use the default
#PBS -q default

# request 1 node
#PBS -l nodes=1:ppn=4
#PBS -l gpus=1
#PBS -l feature=gpu

# request wall time
# (Default is 1 hour without this directive)
#PBS -l walltime=24:00:00

# mail is sent to you when the job starts and when it terminates or aborts
#PBS -m ea

# specify your email address
#PBS -M William.J.Kaufman.20@dartmouth.edu

# By default, PBS scripts execute in your home directory, not the
# directory from which they were submitted. The following line
# places the job in the directory from which the job was submitted.
cd $PBS_O_WORKDIR

conda activate rl_pulse

python -u tf_agents_propagators_PPO.py
